---
author_url: http://joshsdb.github.io/
generator: jekyll 3.0.1
permalink: pretty
paginate: 5 # number of articles on the index
host: 0.0.0.0
detach: false
url: http://freecodecamp.github.io
exclude: 
        - README.md
        - package.json
        - grunt.js
        - Gruntfile.js
        - node_modules
        - bower.js
        - bower_components
        - .env
        - Procfile
        - Gemfile
        - app.json
gems: 
        - jekyll-paginate
